/* Opus megaboard — a grid of looping <video> tiles, each playing an "apex"
 * segment, swapping in a new one as it ends. Continuously cycles until paused.
 *
 * Data comes from playlist.json (generated by `peaks playlist`), with stream
 * URLs already baked in, so this file never touches the Stash GraphQL API.
 */

const State = {
  apexes: [],
  tiles: [],
  playing: true,
  focused: null, // tile currently unmuted (all others stay muted)
};

// --- weighted, no-immediate-repeat picker ---------------------------------

function makePicker(apexes) {
  // Each apex may carry an optional `score`; default 1. Higher score => more
  // likely. We avoid handing the same apex to two tiles back-to-back.
  const weights = apexes.map((a) => Math.max(0.0001, a.score ?? 1));
  const total = weights.reduce((s, w) => s + w, 0);
  let lastIdx = -1;

  return function pick() {
    if (apexes.length === 1) return apexes[0];
    for (let attempt = 0; attempt < 8; attempt++) {
      let r = Math.random() * total;
      let idx = 0;
      while (r > weights[idx] && idx < weights.length - 1) {
        r -= weights[idx];
        idx++;
      }
      if (idx !== lastIdx) {
        lastIdx = idx;
        return apexes[idx];
      }
    }
    return apexes[Math.floor(Math.random() * apexes.length)];
  };
}

let pickApex = () => null;

// --- tiles ----------------------------------------------------------------

function loadApex(tile) {
  const apex = pickApex();
  if (!apex) return;
  const v = tile.video;
  tile.apex = apex;
  tile.mode = "offset"; // re-detected per stream on loadedmetadata
  tile.label.textContent = `#${apex.scene_id} · ${fmt(apex.start)} (${apex.duration.toFixed(0)}s)`;
  v.src = apex.url;
  v.muted = tile !== State.focused;
  v.load();
  if (State.playing) v.play().catch(() => {});
}

function advance(tile) {
  if (!State.playing) return;
  // debounce: timeupdate/ended/error can fire in quick succession near a swap
  const now = performance.now();
  if (tile.lastAdvance && now - tile.lastAdvance < 500) return;
  tile.lastAdvance = now;
  loadApex(tile);
}

function makeTile() {
  const el = document.createElement("div");
  el.className = "tile";

  const video = document.createElement("video");
  video.muted = true;
  video.playsInline = true;
  video.preload = "auto";

  const label = document.createElement("span");
  label.className = "label";

  el.append(video, label);
  const tile = { el, video, label, apex: null, mode: "offset", lastAdvance: 0 };

  // Stash serves two kinds of stream for `?start=`:
  //  - transcoded: playback begins AT the seek point, currentTime counts from
  //    0 within the apex ("offset" mode)
  //  - direct-play: the param is ignored, we get the whole file and
  //    currentTime is absolute file time ("absolute" mode — seek manually)
  // Detect which one we got from the reported duration.
  video.addEventListener("loadedmetadata", () => {
    if (!tile.apex) return;
    if (
      Number.isFinite(video.duration) &&
      video.duration > tile.apex.duration + 5
    ) {
      tile.mode = "absolute";
      video.currentTime = tile.apex.start;
    } else {
      tile.mode = "offset";
    }
  });

  // advance when the segment's worth of playback has elapsed
  video.addEventListener("timeupdate", () => {
    if (!tile.apex) return;
    const end =
      tile.mode === "absolute" ? tile.apex.end : tile.apex.duration;
    if (video.currentTime >= end - 0.25) {
      advance(tile);
    }
  });
  video.addEventListener("ended", () => advance(tile));
  video.addEventListener("error", () => setTimeout(() => advance(tile), 500));

  el.addEventListener("click", () => focusTile(tile));
  return tile;
}

function focusTile(tile) {
  // click a tile to unmute it (and mute whatever was focused before)
  if (State.focused === tile) {
    tile.video.muted = true;
    tile.el.classList.remove("focused");
    State.focused = null;
    return;
  }
  if (State.focused) {
    State.focused.video.muted = true;
    State.focused.el.classList.remove("focused");
  }
  State.focused = tile;
  tile.el.classList.add("focused");
  tile.video.muted = false;
  tile.video.play().catch(() => {});
}

// --- board layout ---------------------------------------------------------

function buildBoard(n) {
  const board = document.getElementById("board");
  board.innerHTML = "";
  board.style.gridTemplateColumns = `repeat(${n}, 1fr)`;
  board.style.gridTemplateRows = `repeat(${n}, 1fr)`;
  State.tiles = [];
  State.focused = null;
  for (let i = 0; i < n * n; i++) {
    const tile = makeTile();
    State.tiles.push(tile);
    board.appendChild(tile.el);
    loadApex(tile);
  }
  updateStatus();
}

// --- controls -------------------------------------------------------------

function setPlaying(on) {
  State.playing = on;
  document.getElementById("toggle").textContent = on ? "Pause" : "Play";
  for (const t of State.tiles) {
    if (on) t.video.play().catch(() => {});
    else t.video.pause();
  }
}

function reshuffle() {
  for (const t of State.tiles) loadApex(t);
}

function updateStatus() {
  document.getElementById("status").textContent =
    `${State.apexes.length} apexes · ${State.tiles.length} tiles`;
}

function fmt(sec) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

function wireControls() {
  document.getElementById("grid").addEventListener("change", (e) => {
    buildBoard(parseInt(e.target.value, 10));
  });
  document.getElementById("toggle").addEventListener("click", () => {
    setPlaying(!State.playing);
  });
  document.getElementById("reshuffle").addEventListener("click", reshuffle);
  document.getElementById("mute").addEventListener("click", () => {
    // an action, not a toggle: silence everything (tiles are muted unless
    // focused, so dropping focus mutes the board)
    if (State.focused) focusTile(State.focused);
  });
}

// --- boot -----------------------------------------------------------------

async function main() {
  let playlist;
  try {
    const res = await fetch("playlist.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    playlist = await res.json();
  } catch (err) {
    return showError(
      "Couldn't load playlist.json.\n\n" +
        "Generate it first:  peaks playlist\n" +
        "Then serve this folder:  peaks serve\n\n" +
        `(${err.message})`
    );
  }
  State.apexes = playlist.apexes || [];
  if (State.apexes.length === 0) {
    return showError(
      `No apexes found for tag "${playlist.tag}".\n\n` +
        "Run `peaks score --write` to create some markers, then `peaks playlist`."
    );
  }
  pickApex = makePicker(State.apexes);
  wireControls();
  buildBoard(parseInt(document.getElementById("grid").value, 10));
}

function showError(msg) {
  const el = document.getElementById("error");
  el.textContent = msg;
  el.hidden = false;
}

main();
